version: '3.8'

# Define services
services:

  # Database Service (MySQL)
  database:
    image: mysql:8.0
    ports:
      - '3306:3306'
    restart: always
    container_name: database-openfeign
    environment:
      MYSQL_DATABASE: open_feign_demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - openfeign-db:/var/lib/mysql

  # phpmyadmin panel
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    restart: always
    environment:
      PMA_HOST: database
    ports:
      - '8090:80'

# Volumes
volumes:
  openfeign-db:
